<?xml version="1.0"?>
<!--
  Hexagon stacks
 -->
<robot name="stack_myrobot2" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot_description)/urdf/common_properties.urdf.xacro"/>
  
  <!-- Xacro properties -->
  <xacro:property name="M_SCALE" value="0.001"/>

  <xacro:property name="default_top_pole_length" value="0.2032" />
  <xacro:property name="pole1_length" value="0.365" />
  <xacro:property name="pole2_length" value="0.0508" />
  <xacro:property name="plate_thickness" value="0.006" />
  
  <!-- Xacro macros -->
  <!-- Pole macros -->
  <xacro:macro name="stack_bottom_pole" params="parent number x_loc y_loc z_loc">
    <joint name="pole_bottom_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="pole_bottom_${number}_link"/>
    </joint>
    <link name="pole_bottom_${number}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/pole_bottom.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0492" radius="0.006"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.008"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.000001686" ixy="0.0" ixz="0.0"
                 iyy="0.000001686" iyz="0.0"
                 izz="0.000000144"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="stack_middle_pole" params="parent number x_loc y_loc z_loc">  
    <joint name="pole_middle_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="pole_middle_${number}_link"/>
    </joint>
    <link name="pole_middle_${number}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/pole_middle.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0608" radius="0.006"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.012"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.000003805" ixy="0.0" ixz="0.0"
                 iyy="0.000003805" iyz="0.0"
                 izz="0.000000216"/>
      </inertial>
    </link>
  </xacro:macro>
  
  <xacro:macro name="stack_top1_pole" params="parent number x_loc y_loc z_loc">  
    <joint name="pole_top1_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="pole_top1_${number}_link"/>
    </joint>
    <link name="pole_top1_${number}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
        <geometry>
          <cylinder length="${pole1_length}" radius="0.006"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${pole1_length}" radius="0.006"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.060"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.000206991" ixy="0.0" ixz="0.0"
                 iyy="0.000206991" iyz="0.0"
                 izz="0.000001080"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="stack_top2_pole" params="parent number x_loc y_loc z_loc">  
    <joint name="pole_top2_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="pole_top2_${number}_link"/>
    </joint>
    <link name="pole_top2_${number}_link">
      <visual>
        <origin xyz=" 0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${pole2_length}" radius="0.006"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${pole2_length}" radius="0.006"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.060"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.000206991" ixy="0.0" ixz="0.0"
                 iyy="0.000206991" iyz="0.0"
                 izz="0.000001080"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- 
    Stack macro - all the components relative transforms are made with respect 
    to the parent link (usually base_link). They could be made relative to each
    other, but there is no necessary reason to do so.
  -->
  <xacro:macro name="stack_myrobot2" params="parent">
    <stack_bottom_pole parent="${parent}" number="0" x_loc= "0.120" y_loc= "0.082" z_loc="0.1028"/>
    <stack_bottom_pole parent="${parent}" number="1" x_loc= "0.055" y_loc= "0.120" z_loc="0.1028"/>
    <stack_bottom_pole parent="${parent}" number="2" x_loc="-0.055" y_loc= "0.120" z_loc="0.1028"/>
    <stack_bottom_pole parent="${parent}" number="3" x_loc= "0.120" y_loc="-0.082" z_loc="0.1028"/>
    <stack_bottom_pole parent="${parent}" number="4" x_loc= "0.055" y_loc="-0.120" z_loc="0.1028"/>
    <stack_bottom_pole parent="${parent}" number="5" x_loc="-0.055" y_loc="-0.120" z_loc="0.1028"/>
    
    <joint name="plate_bottom_joint" type="fixed">
      <origin xyz="0.02364 0.0 0.1306" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="plate_bottom_link"/>
    </joint>  
    <link name="plate_bottom_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/plate_bottom.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="-0.02364 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${plate_thickness}" radius="0.170"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.520" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003328" ixy="0.0" ixz="0.0"
                 iyy="0.003328" iyz="0.0"
                 izz="0.006656" />
      </inertial>
    </link>
    
    <stack_middle_pole parent="${parent}" number="0" x_loc= "0.0381" y_loc= "0.1505" z_loc="0.1640"/>
    <stack_middle_pole parent="${parent}" number="1" x_loc= "0.0381" y_loc="-0.1505" z_loc="0.1640"/>
    <stack_middle_pole parent="${parent}" number="2" x_loc="-0.0381" y_loc= "0.1505" z_loc="0.1640"/>
    <stack_middle_pole parent="${parent}" number="3" x_loc="-0.0381" y_loc="-0.1505" z_loc="0.1640"/>
    
    <joint name="plate_middle_joint" type="fixed">
      <origin xyz="-0.01364 0.0 0.1874" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="plate_middle_link"/>
    </joint>  
    <link name="plate_middle_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/plate_middle.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="0.01364 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${plate_thickness}" radius="0.170"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.520" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003328" ixy="0.0" ixz="0.0"
                 iyy="0.003328" iyz="0.0"
                 izz="0.006656" />
      </inertial>  
    </link>

    <stack_top1_pole parent="${parent}" number="0" x_loc= "0.0381" y_loc= "0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length/2.0}"/>
    <stack_top1_pole parent="${parent}" number="1" x_loc= "0.0381" y_loc="-0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length/2.0}"/>
    <stack_top1_pole parent="${parent}" number="2" x_loc="-0.0381" y_loc= "0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length/2.0}"/>
    <stack_top1_pole parent="${parent}" number="3" x_loc="-0.0381" y_loc="-0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length/2.0}"/>

    <joint name="plate_top1_joint" type="fixed">
      <origin xyz="-0.01364 0.0  ${0.2920 - default_top_pole_length/2.0 + pole1_length + plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="plate_top1_link"/>
    </joint>  
    <link name="plate_top1_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/plate_top.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="0.01364 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${plate_thickness}" radius="0.170"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.520"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.003328" ixy="0.0" ixz="0.0"
                 iyy="0.003328" iyz="0.0"
                 izz="0.006656" />
      </inertial>
    </link>

    <stack_top2_pole parent="${parent}" number="0" x_loc= "0.0381" y_loc= "0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length + pole2_length/2.0 + plate_thickness}"/>
    <stack_top2_pole parent="${parent}" number="1" x_loc= "0.0381" y_loc="-0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length + pole2_length/2.0 + plate_thickness}"/>
    <stack_top2_pole parent="${parent}" number="2" x_loc="-0.0381" y_loc= "0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length + pole2_length/2.0 + plate_thickness}"/>
    <stack_top2_pole parent="${parent}" number="3" x_loc="-0.0381" y_loc="-0.1505" z_loc="${0.2920 - default_top_pole_length/2.0 + pole1_length + pole2_length/2.0 + plate_thickness}"/>
    
    <joint name="plate_top2_joint" type="fixed">
      <origin xyz="-0.01364 0.0  ${0.2920 - default_top_pole_length/2.0 + pole1_length + plate_thickness + pole2_length + plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="plate_top2_link"/>
    </joint>
    <link name="plate_top2_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/plate_top.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="0.01364 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${plate_thickness}" radius="0.170"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.520"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.003328" ixy="0.0" ixz="0.0"
                 iyy="0.003328" iyz="0.0"
                 izz="0.006656" />
      </inertial>
    </link>

    <!-- joint for D455_top1 camera on the plate_top1 -->
    <joint name="plate_top1_front_joint" type="fixed">
      <origin xyz="${0.003 + 0.09525 + 0.014} 0.0  ${plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="plate_top1_link"/>
      <child link="plate_top1_front_link"/>
    </joint>
    <link name="plate_top1_front_link">
    </link>

    <!-- joint for VLP-16  on the plate_top2 -->
    <joint name="plate_top2_center_joint" type="fixed">
      <origin xyz="${0.003 + 0.014} 0.0  ${plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="plate_top2_link"/>
      <child link="plate_top2_center_link"/>
    </joint>
    <link name="plate_top2_center_link">
    </link>

    <!-- <joint name="plate_top1_center_joint" type="fixed">
      <origin xyz="{0.003 + 0.014} 0.0  ${0.2920 - pole2_length/2.0 + pole1_length + plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="plate_top1_center_link"/>
    </joint>
    <link name="plate_top1_center_link">
    </link> -->

    <!-- <joint name="plate_top2_front_joint" type="fixed">
      <origin xyz="${0.003 + 0.09525 + 0.014} 0.0  ${plate_thickness/2.0}" rpy="0 0 0"/>
      <parent link="plate_top2_link"/>
      <child link="plate_top2_front_link"/>
    </joint>
    <link name="plate_top2_front_link">
    </link> -->


  </xacro:macro>
</robot>
